redshift_reports:
  outputs:
    dev:
      dbname: reports
      host: "{{ env_var('DBT_REDSHIFT_HOST_REPORTING_STG') }}"
      password: "{{ env_var('DBT_REDSHIFT_APP_PASSWORD_REPORTING_STG') }}"
      port: 5439
      schema: dev
      threads: 2
      type: redshift
      user: dbt_user
    prod:
      dbname: reports
      host: "{{ env_var('DBT_REDSHIFT_HOST_REPORTING_PROD') }}"
      password: "{{ env_var('DBT_REDSHIFT_APP_PASSWORD_PROD') }}"
      port: 5439
      schema: public
      threads: 2
      type: redshift
      user: dbt_user

    staging:
      dbname: reports
      host: "{{ env_var('DBT_REDSHIFT_HOST_REPORTING_STG') }}"
      password: "{{ env_var('DBT_REDSHIFT_APP_PASSWORD_REPORTING_STG') }}"
      port: 5439
      schema: public
      threads: 2
      type: redshift
      user: dbt_user
  target: staging