redshift_reports:
  outputs:
    dev:
      dbname: "{{ env_var('REDSHIFT_DBNAME_STG') }}"
      host: "{{ env_var('REDSHIFT_HOST_REPORTING_STG') }}"
      password: "{{ env_var('REDSHIFT_APP_PASSWORD_STG') }}"
      port: 5439
      schema: dev
      threads: 2
      type: redshift
      user: dbt_stg
    prod:
      dbname: "{{ env_var('REDSHIFT_DBNAME_PROD') }}"
      host: "{{ env_var('REDSHIFT_HOST_REPORTING_PROD') }}"
      password: "{{ env_var('REDSHIFT_APP_PASSWORD_PROD') }}"
      port: 5439
      schema: public
      threads: 2
      type: redshift
      user: dbt_prod
    staging:
      dbname: "{{ env_var('REDSHIFT_DBNAME_STG') }}"
      host: "{{ env_var('REDSHIFT_HOST_REPORTING_STG') }}"
      password: "{{ env_var('REDSHIFT_APP_PASSWORD_REPORTING_STG') }}"
      port: 5439
      schema: "{{ env_var('WAREHOUSE_SCHEMA_NAME', 'public') }}"
      threads: 2
      type: redshift
      user: reports_user
  target: staging