redshift_reports:
  outputs:
    dev:
      dbname: ${REDSHIFT_DBNAME_STG}
      host: ${REDSHIFT_HOST_REPORTING_STG}
      password: ${REDSHIFT_APP_PASSWORD_STG}
      port: 5439
      schema: dev
      threads: 2
      type: redshift
      user: dbt_stg
    prod:
      dbname: ${REDSHIFT_DBNAME_PROD}
      host: ${REDSHIFT_HOST_REPORTING_PROD}
      password: ${REDSHIFT_APP_PASSWORD_PROD}
      port: 5439
      schema: public
      threads: 2
      type: redshift
      user: dbt_prod
    staging:
      dbname: ${REDSHIFT_DBNAME_STG}
      host: ${REDSHIFT_HOST_REPORTING_STG}
      password: ${REDSHIFT_APP_PASSWORD_STG}
      port: 5439
      schema: public
      threads: 2
      type: redshift
      user: dbt_stg
  target: staging
  
