select
    id as line_item_id,
    billing_status as li_billing_status,
    code as billing_code,
    description,
    procedure_type,
    quantity,
    price,
    allowed,
    adjustment,
    ins1_paid,
    ins2_paid,
    ins3_paid,
    pt_paid,
    balance_ins,
    balance_pt,
    resp_ins,
    resp_pt,
    billing_profile_id,
    expected_reimbursement,
    appointment_id,
    coalesce(billed, 0) as billed,
    convert_timezone('EST', 'UTC', created_at) as li_created_at,
    updated_at as li_updated_at
from {{ source("chronometer_production", "billing_billinglineitem") }}
WHERE _fivetran_deleted is false
