{%- macro exam_room_name() -%}
    decode(
        a.examination_room,
        1,
        o.exam_room_1_name,
        2,
        o.exam_room_2_name,
        3,
        o.exam_room_3_name,
        4,
        o.exam_room_4_name,
        5,
        o.exam_room_5_name,
        6,
        o.exam_room_6_name,
        7,
        o.exam_room_7_name,
        8,
        o.exam_room_8_name,
        9,
        o.exam_room_9_name,
        10,
        o.exam_room_10_name,
        11,
        o.exam_room_11_name,
        12,
        o.exam_room_12_name,
        13,
        o.exam_room_13_name,
        14,
        o.exam_room_14_name,
        15,
        o.exam_room_15_name,
        ''
    ) as exam_room_name
{%- endmacro -%}
