{%- macro exam_room_name(appt_tbl, office_tbl) -%}
    decode(
        {{ appt_tbl }}.examination_room,
        1,
        {{ office_tbl }}.exam_room_1_name,
        2,
        {{ office_tbl }}.exam_room_2_name,
        3,
        {{ office_tbl }}.exam_room_3_name,
        4,
        {{ office_tbl }}.exam_room_4_name,
        5,
        {{ office_tbl }}.exam_room_5_name,
        6,
        {{ office_tbl }}.exam_room_6_name,
        7,
        {{ office_tbl }}.exam_room_7_name,
        8,
        {{ office_tbl }}.exam_room_8_name,
        9,
        {{ office_tbl }}.exam_room_9_name,
        10,
        {{ office_tbl }}.exam_room_10_name,
        11,
        {{ office_tbl }}.exam_room_11_name,
        12,
        {{ office_tbl }}.exam_room_12_name,
        13,
        {{ office_tbl }}.exam_room_13_name,
        14,
        {{ office_tbl }}.exam_room_14_name,
        15,
        {{ office_tbl }}.exam_room_15_name,
        ''
    ) as exam_room_name
{%- endmacro -%}

