name: DBT CI

on:
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: [self-hosted, macOS] 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install
    - name: Load .env
      run: |
        set -a
        source source ${GITHUB_WORKSPACE}/.env
        set +a
    - name: Run dbt compile
      run: |
        pipenv run dbt compile --profiles-dir .
    - name: Run dbt test
      run: |
        pipenv run dbt test --profiles-dir .
