name: DBT CI

on:
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: [self-hosted, macOS] 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install
    - name: Use Secrets
      run: |
        export REDSHIFT_APP_PASSWORD_REPORTING_STG=${{ secrets.REDSHIFT_APP_PASSWORD_REPORTING_STG }}
        export REDSHIFT_DBNAME_STG=${{ secrets.REDSHIFT_DBNAME_STG }}
        export REDSHIFT_HOST_REPORTING_STG=${{ secrets.REDSHIFT_HOST_REPORTING_STG }}
    - name: Run dbt compile
      run: |
        pipenv run dbt compile --profiles-dir .
    - name: Run dbt test
      run: |
        pipenv run dbt test --profiles-dir .
